import _isNaN from 'lodash.isnan';

const traversed = new WeakSet();

export default function({ types: t, template }) {
  const buildIsString = template(`typeof V === 'string' || Object.prototype.toString.call(V) === '[object String]'`);

  const buildStringIndexer = (() => {
    const tmpl = template(`STRING.charAt(INDEX)`);
    return (expr) => {
      return tmpl({
        STRING: expr.object,
        INDEX: t.NumericLiteral(+expr.property.value)
      })
    };
  })();

  const buildIdentfierIndexer = (() => {
    const tmpl = template(`ISSTRINGOBJECT ? OBJECT.charAt(INDEX) : MEMBEREXPRESSION`);
    return (expr) => {
      return tmpl({
        OBJECT: expr.object,
        INDEX: t.NumericLiteral(+expr.property.value),
        MEMBEREXPRESSION: expr,
        ISSTRINGOBJECT: buildIsString({ V: expr.object })
      });
    };
  })();

  function isIndex(n) {
    return (
      t.isNumericLiteral(n) ||
      (t.isStringLiteral(n) &&
       (+n.value).toString() === n.value &&
       !_isNaN(+n.value))
    );
  }

  return {
    visitor: {
      MemberExpression: {
        exit(path) {
          const { node, parent, scope } = path;

          // skip if left value
          if(t.isAssignmentExpression(parent) && node === parent.left) {
            return;
          }

          // skip if dotted notation
          if(!node.computed) {
            return;
          }

          // skip if generated by this plugin
          if(traversed.has(node)) {
            return;
          }
          traversed.add(node);

          const {
            object: o,
            property: p
          } = node;

          let replacement;

          if(t.isStringLiteral(o)) {
            if(isIndex(p)) {
              // "str"[0], "str"["1"], not "str"[''], "str"['02']
              replacement = buildStringIndexer(node);
            }
          } else if(t.isIdentifier(o)) {
            if(isIndex(p)) {
              // a[0], a["1"], not a[''], a['02']
              replacement = buildIdentfierIndexer(node);
            }
          }

          if(replacement) {
            path.replaceWith(replacement);
          }
        }
      }
    }
  };
}
